#include <a_samp>
#include <a_mysql>
#include <defines>
#include <macros>
#include <states>
#include <db_core>
#include <logger>
#include <ui_core>
#include <player_core>
#include <phone_core>
main() {}
